### PR TITLE
feat: additionals

### PR DESCRIPTION
**Pull request by Rendevior**
## Description

Supports another subtitle file type, and general bug fixes, also added formattings

## Checklist

Please review and complete these items before submitting your pull request:

- [x] I have tested my changes thoroughly and they work as expected.
- [x] I have included appropriate tests for any new features or bug fixes.
- [x] My code is well-formatted and complies with the ShellCheck standards.
- [ ] I have updated the documentation (if applicable).
- [x] I have read and agree to the [code of conduct](CODE_OF_CONDUCT.md) and [contribution guidelines](CONTRIBUTING.md).

## Screenshots (if applicable)

None

## Additional Notes (if applicable)

None

### CODE REVIEW

**Comment by fearocanity** [comment]
Should i do the rest?

**Comment by Rendevior** [comment]
> Should i do the rest?

Leave it to me 😎

**Comment by Rendevior** [comment]
> Should i do the rest?

Nevermind, do it😅

**Comment by fearocanity** [comment]
I did an oopsie, I accidentally pushed something in master😭

**Pull request merged**
